---
- name: Deploy Artifactory, see https://github.com/goern/artifactory-on-openshift
  tags:
    - openshift
    - artifactory
    - deploy

  hosts: localhost
  vars: # FIXME DRY
    openshift_master_url: "{{ lookup('env','OCP_URL') }}"
    username: "{{ lookup('env','OCP_USER') }}"
    password: "{{ lookup('env','OCP_PASSWORD') }}"
    project_name: nginx-revproxy-test

  tasks:
  - name: verify oc version
    shell: "oc version"
    register: command_result
    failed_when:
      - "'oc v1.3.1' not in command_result.stdout"
      - "'oc v3.3' not in command_result.stdout"

  - name: login to OpenShift as administrator
    command: "oc login --insecure-skip-tls-verify=true -u {{ username }} -p {{ password }} {{ openshift_master_url }}"

  - name: "make sure to use project {{ project_name }}"
    command: "oc project {{ project_name }}"
    register: project_exists
    ignore_errors: true

  - name: "create project {{ project_name }}"
    command: "oc new-project {{ project_name }}"
    when: project_exists | failed

  - name: create template for artifactory
    command: oc create -f test-template.yaml
    register: test_template_rc
    ignore_errors: true

  - name: replace existing template for artifactory
    command: oc replace -f test-template.yaml
    when: test_template_rc | failed

  - name: create reverse-proxy test application
    command: oc new-app --template=nginx-rev-proxy-test
