---
kind: Template
apiVersion: v1
labels:
  version: 1.0.0
  group: test
metadata:
  annotations:
    description: Just a Test, rh-nginx18, OpenShift Container Platform 3.3, a reverse proxy
    tags: instant-app,test,nginx,reverse_proxy
    version: 1.0.0
  name: nginx-rev-proxy-test
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: s2i-nginx
    description: "This is a s2i for nginx 1.8"
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: reverse-proxy
    description: "This is a nginx reverse-proxy"
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: upstream-server
    description: "This is a nginx upstream-server"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: s2i-nginx
  spec:
    triggers:
      -
        type: ConfigChange
    source:
      type: Git
      git:
        uri: https://github.com/goern/s2i-nginx
    strategy:
      type: Docker
      dockerStrategy:
    output:
      to:
        kind: ImageStreamTag
        name: s2i-nginx:latest
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: reverse-proxy
  spec:
    triggers:
      -
        type: ImageChange
        imageChange:
      -
        type: imagechange
        imageChange:
          from:
            kind: ImageStreamTag
            name: s2i-nginx:latest
    source:
      type: Git
      git:
        uri: https://github.com/goern/nginx-rev-proxy-test
        ref: reverse-proxy
    strategy:
      type: Source
      sourceStrategy:
         from:
           kind: ImageStreamTag
           name: s2i-nginx:latest
    output:
      to:
        kind: ImageStreamTag
        name: reverse-proxy:latest
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: upstream-server
  spec:
    triggers:
      -
        type: ImageChange
        imageChange:
      -
        type: imagechange
        imageChange:
          from:
            kind: ImageStreamTag
            name: s2i-nginx:latest
    source:
      type: Git
      git:
        uri: https://github.com/goern/nginx-rev-proxy-test
        ref: upstream-server
    strategy:
      type: Source
      sourceStrategy:
         from:
           kind: ImageStreamTag
           name: s2i-nginx:latest
    output:
      to:
        kind: ImageStreamTag
        name: upstream-server:latest
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: reverse-proxy
    annotations:
      description: This is the reverse proxy
  spec:
    strategy:
      type: Rolling
    triggers:
      - type: ImageChange
        imageChangeParams:
          containerNames:
            - reverse-proxy
          from:
            kind: ImageStreamTag
            name: reverse-proxy:latest
      - type: ConfigChange
    replicas: 1
    selector:
      name: reverse-proxy
    template:
      metadata:
        name: reverse-proxy
        labels:
          name: reverse-proxy
      spec:
        containers:
          - name: reverse-proxy
            image: ' '
            ports:
              - containerPort: 8080
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 5
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 2
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 5
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 2
            resources:
              limits:
                cpu: 25m
                memory: 16Mi
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: upstream-server
    annotations:
      description: This is the upstream server
  spec:
    strategy:
      type: Rolling
    triggers:
      - type: ImageChange
        imageChangeParams:
          containerNames:
            - upstream-server
          from:
            kind: ImageStreamTag
            name: upstream-server:latest
      - type: ConfigChange
    replicas: 1
    selector:
      name: upstream-server
    template:
      metadata:
        name: upstream-server
        labels:
          name: upstream-server
      spec:
        containers:
          - name: upstream-server
            image: ' '
            ports:
              - containerPort: 8080
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 5
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 2
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 5
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 2
            resources:
              limits:
                cpu: 25m
                memory: 16Mi
